name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH=$HOME/.fly/bin:$PATH

      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly auth token $FLY_API_TOKEN

      - name: Deploy to Fly.io
        run: fly deploy